### ISSUE TITLE
code converter not found (UTF-8 to ISO-8859-1)

### ISSUE THREAD

**Issue by mvidner** [yast/yast-ruby-bindings#133]
This code

``` ruby
# encoding: utf-8
puts "schön".encode(Encoding::ISO_8859_1)
```

works just fine, printing a substitution character (�), when run with `ruby test.rb`.
But when run with `.../y2base ./test.rb testsuite`, it fails with an exception "code converter not found (UTF-8 to ISO-8859-1)"

I have found that it is caused by our code not calling `Init_enc` which is normally called from [`process_options`](https://github.com/ruby/ruby/blob/1b13e1e6984713db91e616506f1167debbc1e79f/ruby.c#L1367)

That function does so much, wtf, I am not sure we want to call it, even with some dummy empty options. A workaround is to require these from ruby code:

``` ruby
require "enc/encdb.so"
require "enc/trans/transdb.so"
```

**Comment by mvidner** [comment]
@lslezak hit this again. We should just add the two `require`s somewhere, probably to src/ruby/yast/yast.rb

**Comment by jreidinger** [comment]
I think C code part will be better

**Comment by jreidinger** [comment]
as you can also use just part of yast

**Comment by lslezak** [comment]
JFYI: I want to fix [bug#932014](https://bugzilla.suse.com/show_bug.cgi?id=932014) in https://github.com/yast/yast-ruby-bindings/blob/master/src/ruby/yast/logger.rb#L6.

**Comment by lslezak** [comment]
I have added the workaround into https://github.com/yast/yast-ruby-bindings/pull/158.

However, it was fixed in a Ruby file, not in the C part. All my attempts to move it into the C part failed,  see https://github.com/yast/yast-ruby-bindings/pull/158#discussion-diff-49319430 for more details.

Feel free to improve it further...

**Comment by mvidner** [comment]
y2base was replaced by y2start in https://github.com/yast/yast-ruby-bindings/pull/191
