### ISSUE TITLE
texts not translated: LANG is ignored

### ISSUE THREAD

**Issue by mvidner** [yast/yast-ruby-bindings#68]
On my workstation with rpms from YaST:Head:ruby, `LANG=cs_CZ.UTF-8 yast2 mouse` shows the texts in English (except the Qt Napoveda(Help) button).

Some digging revealed that `Yast::I18n::current_language` returns DEFAULT_LOCALE (en_US) because `WFM::GetLanguage` returns an empty string.

**Comment by jreidinger** [comment]
should be already fixed, if not please reopen.
