### ISSUE TITLE
Adding of custom module path

### ISSUE THREAD

**Issue by vmoravec** [yast/yast-ruby-bindings#72]
Module `Yast` has the public singleton method `add_module_path` which I think is supposed to extend the module load paths. It works as expected but:
- As documented here [1] the recomended way for testing is to set properly Y2DIR env var, which is kind of impractical while writing/running ruby tests for yast modules
- The return value of `Yast.y2paths` does not reflect changes which `Yast.add_module_path` has done
- It is not clear whether the new path has been added to index 0 or -1 or some other in the list returned by `Yast.y2paths` . I would expect to find it on position 0, because when I would want to run some tests, I want ruby/yast to load the files from my local repository and ignore the source files installed on the system (in case the `Yast.import` method works similar to ruby's `require` and stops searching when the file has been found).

[1] https://github.com/yast/yast-ruby-bindings/blob/master/src/binary/Yast.cc#L304

**Comment by jreidinger** [comment]
drop for api in https://github.com/yast/yast-ruby-bindings/pull/187

**Comment by jreidinger** [comment]
fix merged
