### ISSUE TITLE
Yast.import consumes raised exceptions

### ISSUE THREAD

**Issue by vmoravec** [yast/yast-ruby-bindings#92]
Using `Yast.import` gives a bit misleading results when there is some exception raised during loading of the target file.

Example:

``` ruby
module Yast
  class TestModule < Module
    raise "This exception will remain hidden"
  end
  Test = TestModule.new
end
```

Trying to import such file will result in exception saying: `NameError: component cannot import namespace 'Test'`. The correct exception is however logged into `/var/log/YaST2/y2log`, but that's not always available (Jenkins). Additionally this might be confusing for yast newcomers or even skilled ruby devs who are not used to look into the yast log file.

**Comment by jreidinger** [comment]
fix merged, thanks for report
